### ISSUE TITLE
2.1 Method should return List<Tourist__c>

### ISSUE THREAD

**Issue by NikitaErmakSenla** [Mechanikm/sf-senla-courses#1]
https://github.com/Mechanikm/sf-senla-courses/blob/ce198087f683b45ed15fade89dfa19d61156e9e3/lecture_2.2/2.%20TouristManager.cls#L2

**Comment by Mechanikm** [comment]
I fixed it. Now the method return this:
00:29:58:021 USER_DEBUG [3]|DEBUG|(Tourist__c:{Name=Vasya Nepupkin, Age__c=10, Id=a005g00002pZoHZAA0}, Tourist__c:{Name=Vasya Pupkin, Age__c=18, Id=a005g00002pZoHUAA0})
