### ISSUE TITLE
2.2.2 L96-106 should belong to TouristService 

### ISSUE THREAD

**Issue by NikitaErmakSenla** [Mechanikm/sf-senla-courses#12]
https://github.com/Mechanikm/sf-senla-courses/blob/8c1e9882f0d0a9d639e6b82305ff174a47c0454d/lecture_2.2/TouristManager.cls#L79

**Comment by NikitaErmakSenla** [comment]
Manager classes should be used only as DB connection and responsible for building SOQL / SOSL queries and returing data

**Comment by Mechanikm** [comment]
Fixed

**Comment by NikitaErmakSenla** [comment]
Still relevant. 
Instead of _'List<Tourist__c> newTourists'_ param method should have '_emails_' and '_names_' params

**Comment by NikitaErmakSenla** [comment]
L102-109 - also to TouristService

**Comment by Mechanikm** [comment]
Fixed (maybe). I remade method, but don't quite understand "method should have 'emails' and 'names' params"

**Comment by NikitaErmakSenla** [comment]
More preferrable method signature:
`public static List<Tourist__c> getFilterByNameEmail (Set<String> names, Set<String> emails) {`
