### ISSUE TITLE
2.3.1 Where this method is used?

### ISSUE THREAD

**Issue by NikitaErmakSenla** [Mechanikm/sf-senla-courses#17]
https://github.com/Mechanikm/sf-senla-courses/blob/8c1e9882f0d0a9d639e6b82305ff174a47c0454d/lecture_2.3/FligfhtValidation.cls#L16

**Comment by Mechanikm** [comment]
Not anywhere. This is for more opportunities I thought.

**Comment by Mechanikm** [comment]
Fixed
