### ISSUE TITLE
2.3.1 Move literals to Constants class

### ISSUE THREAD

**Issue by NikitaErmakSenla** [Mechanikm/sf-senla-courses#19]
https://github.com/Mechanikm/sf-senla-courses/blob/8c1e9882f0d0a9d639e6b82305ff174a47c0454d/lecture_2.3/FligfhtValidation.cls#L7

**Comment by Mechanikm** [comment]
I hope I got it right
https://gorbeia.wordpress.com/2015/03/11/java-enums-vs-constants/

**Comment by Mechanikm** [comment]
Fixed
