### ISSUE TITLE
2.3.1 Do fields Trip__r.StartDate__c and Tourist__r.Birthdate__c have any values?

### ISSUE THREAD

**Issue by NikitaErmakSenla** [Mechanikm/sf-senla-courses#23]
https://github.com/Mechanikm/sf-senla-courses/blob/8c1e9882f0d0a9d639e6b82305ff174a47c0454d/lecture_2.3/FligfhtValidation.cls#L9

**Comment by Mechanikm** [comment]
![изображение](https://user-images.githubusercontent.com/77673018/112615331-69891580-8e33-11eb-9155-a931fcf7f2de.png)
It is some problems with curtain tourists. I'll rewrite the code.

**Comment by Mechanikm** [comment]
Fixed
