### ISSUE TITLE
Please remove this string

### ISSUE THREAD

**Issue by ekevra** [Mechanikm/sf-senla-courses#45]
https://github.com/Mechanikm/sf-senla-courses/blob/f944abb8f4a961699ea2d10146d22e9072bf6958/lecture_2.5/TouristTriggerHandler.cls#L9

По-моему, эта проверка здесь лишняя: записи только пришла из БД(их айдишки), а мы снова проверяем, есть они в бд или нету.

**Comment by Mechanikm** [comment]
На тот случай, если дубликаты отсутствуют.
Или это излишняя предосторожность при таком варианте?

**Comment by ekevra** [comment]
Я считаю, что да)

**Comment by ekevra** [comment]
Так, я подумала ещё разок и решила, что я уверена в этом
