### ISSUE TITLE
SOQL issue

### ISSUE THREAD

**Issue by ekevra** [Mechanikm/sf-senla-courses#51]
https://github.com/Mechanikm/sf-senla-courses/blob/5c105982b89229d27c612a172a084776fd29ff32/lecture_2.5/FlightDeleterBatch.cls#L3

Why '!=' ?
Should be '>'

**Comment by Mechanikm** [comment]
Because in this way I cut off flights, that NOT been created in the last 30 days. They are older 30 days or... should make in a future.
I'll change '!=' anyway
